name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: dylanvann/publish-github-action@973d5c2eec5df00513bb013e4424eaf04117ebd1 # v1.1.49
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
