name: Test
on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: yarn install --frozen-lockfile
      - run: yarn run yarn-deduplicate --strategy fewer --fail
      - run: yarn run build
      - run: yarn run prettier --check
      - run: yarn run xo
